"""initial schema

Revision ID: aa80f1838f9d
Revises: 
Create Date: 2026-05-26 09:53:01.768565
"""

from alembic import op
import sqlalchemy as sa


revision = 'aa80f1838f9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('operadora', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('centros_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('subarea', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('rubricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('natureza', sa.String(length=100), nullable=True),
    sa.Column('incide_inss', sa.Boolean(), nullable=False),
    sa.Column('incide_fgts', sa.Boolean(), nullable=False),
    sa.Column('incide_irrf', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=512), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tabela', sa.String(length=255), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('campo_alterado', sa.String(length=255), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('origem', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencias_folha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('usuario_fechamento_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_fechamento_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_importacao', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_linhas', sa.Integer(), nullable=True),
    sa.Column('linhas_importadas', sa.Integer(), nullable=True),
    sa.Column('linhas_com_erro', sa.Integer(), nullable=True),
    sa.Column('relatorio_erros', sa.JSON(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cbo', sa.String(length=20), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folha_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('total_proventos', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_descontos', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_encargos', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_beneficios', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_liquido_estimado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_custo_empresa', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('quantidade_colaboradores', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competencia_id'], ['competencias_folha.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia_id')
    )
    op.create_table('colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('nome_social', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=30), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('regime_contratual', sa.String(length=50), nullable=True),
    sa.Column('tipo_vinculo', sa.String(length=50), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('centro_custo_id', sa.Integer(), nullable=True),
    sa.Column('salario_base', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('jornada_semanal', sa.Float(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_colaboradores_cpf'), 'colaboradores', ['cpf'], unique=False)
    op.create_table('admissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('data_prevista_admissao', sa.Date(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('checklist_json', sa.JSON(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('afastamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('quantidade_dias', sa.Float(), nullable=True),
    sa.Column('quantidade_horas', sa.Float(), nullable=True),
    sa.Column('impacta_folha', sa.Boolean(), nullable=False),
    sa.Column('impacta_absenteismo', sa.Boolean(), nullable=False),
    sa.Column('cid_mascarado', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colaborador_beneficios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('beneficio_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor_empresa', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_colaborador', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('dependentes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beneficio_id'], ['beneficios.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desligamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('data_aviso_previo', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('tipo_rescisao', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('exame_demissional', sa.Boolean(), nullable=False),
    sa.Column('entrevista_realizada', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('valor_estimado_rescisao', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_armazenado', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('hash_arquivo', sa.String(length=128), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('usuario_upload_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['usuario_upload_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ferias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('periodo_aquisitivo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_aquisitivo_fim', sa.Date(), nullable=True),
    sa.Column('data_limite_gozo', sa.Date(), nullable=True),
    sa.Column('dias_direito', sa.Float(), nullable=True),
    sa.Column('dias_gozados', sa.Float(), nullable=True),
    sa.Column('dias_restantes', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('abono_pecuniario', sa.Boolean(), nullable=False),
    sa.Column('adiantamento_13', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_funcional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('campo_alterado', sa.String(length=255), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_funcional_colaborador_id'), 'historico_funcional', ['colaborador_id'], unique=False)
    op.create_table('lancamentos_folha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('rubrica_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['competencia_id'], ['competencias_folha.id'], ),
    sa.ForeignKeyConstraint(['rubrica_id'], ['rubricas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamentos_folha')
    op.drop_index(op.f('ix_historico_funcional_colaborador_id'), table_name='historico_funcional')
    op.drop_table('historico_funcional')
    op.drop_table('ferias')
    op.drop_table('documentos')
    op.drop_table('desligamentos')
    op.drop_table('colaborador_beneficios')
    op.drop_table('afastamentos')
    op.drop_table('admissoes')
    op.drop_index(op.f('ix_colaboradores_cpf'), table_name='colaboradores')
    op.drop_table('colaboradores')
    op.drop_table('folha_snapshots')
    op.drop_table('cargos')
    op.drop_table('importacoes')
    op.drop_table('departamentos')
    op.drop_table('competencias_folha')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('rubricas')
    op.drop_table('empresas')
    op.drop_table('centros_custo')
    op.drop_table('beneficios')
    # ### end Alembic commands ###
